### ISSUE TITLE
Organising application forms

### ISSUE THREAD

**Issue by poldham** [poldham/permit_system#5]
Maybe to be transparent to the authorities we should compile all the questions in the form into one spreadsheet (using cut and paste) with something like the following headers

1. Question
2. Authority (KWS, KEPHIS etc)
3. Form identifier (A, B etc)
4. Type (to be elaborated e.g. meta, qualitative, quantitative, geographic etc)

That way we would be able to see which authorities ask for the same basic information (name, address etc) and which are distinctive to the authority. Importantly, it would provide a means to show the relevant authorities that all of their questions have been taken into account in the design process. We could also show amendments and merges in a column. 

The question is: who will do this? @Jonasangoro @salesiokiura could Amband task a member of staff with this? It will not be very exciting to do, but it will be important. 

@hartmut-meyer has joined us on Github. Welcome Hartmut!

Note that all communications on Github are public.

**Comment by salesiokiura** [comment]
Hi,
I agree with you @poldham . we can do this from this from here based on the forms and interaction with the IT guys of each organization.

Hopefully we get an sqldump of ORIS, that application has captured much of the form details. In our workshop in March 2017 we had generated the docs below. Is the information relevant?

[common features from organizational processes.docx](https://github.com/poldham/permit_system/files/1554113/common.features.from.organizational.processes.docx)
[Distinct requirements and features per organization in the process.docx](https://github.com/poldham/permit_system/files/1554114/Distinct.requirements.and.features.per.organization.in.the.process.docx)
